#!/usr/bin/env bash
set -e

ROOT="/opt/side/bravesoul-game"
cd "$ROOT"
mkdir -p proofs/combat_feel

DISP=":94"
killall -9 Xvfb 2>/dev/null || true
sleep 1

Xvfb "$DISP" -screen 0 1280x720x24 -nolisten tcp >/tmp/xvfb94.log 2>&1 &
XVFB_PID=$!

READY_FLAG="/tmp/godot_combat_ready.flag"
SYNC_FLAG="/tmp/ffmpeg_started.flag"
rm -f "$READY_FLAG" "$SYNC_FLAG" 2>/dev/null || true

cleanup() {
    kill "$XVFB_PID" 2>/dev/null || true
    rm -f "$READY_FLAG" "$SYNC_FLAG" 2>/dev/null || true
}
trap cleanup EXIT

sleep 1

OUT_MP4="proofs/combat_feel/macaque_combat.mp4"

echo "=== STARTING GODOT IN BACKGROUND ==="
DISPLAY="$DISP" godot --path game --rendering-driver opengl3 -s res://scripts/dev/run_macaque_combat_showcase.gd >/tmp/godot_macaque.log 2>&1 &
GODOT_PID=$!

WAITED=0
while [ ! -f "$READY_FLAG" ] && [ "$WAITED" -lt 80 ]; do
    sleep 0.1
    WAITED=$((WAITED + 1))
    if ! kill -0 "$GODOT_PID" 2>/dev/null; then
        echo "Godot died early! Log:"
        cat /tmp/godot_macaque.log
        exit 1
    fi
done
echo "Godot ready flag detected in ${WAITED}00ms"

echo "=== LAUNCHING FFMPEG RECORDING (3.5s) ==="
ffmpeg -y -loglevel error -f x11grab -draw_mouse 0 -framerate 30 -video_size 1280x720 -i "$DISP" \
       -t 3.5 -c:v libx264 -preset veryfast -pix_fmt yuv420p "$OUT_MP4" &
FF_PID=$!

sleep 0.2
touch "$SYNC_FLAG"
echo "Sync flag touched! Godot will now run the combat sequence."

wait "$FF_PID" || true
wait "$GODOT_PID" || true

echo "=== RECORDING FINISHED ==="
ls -lh "$OUT_MP4"

echo "=== VERIFIED PROOFS GENERATED BY ENGINE ==="
ls -lh proofs/combat_feel/macaque_real_*.png
